apiVersion: skaffold/v4beta9
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: nightofserenity/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: nightofserenity/comments
      context: comments
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: nightofserenity/event-bus
      context: event-bus
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: nightofserenity/moderation
      context: moderation
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: nightofserenity/posts
      context: posts
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: nightofserenity/query
      context: query
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
# old version
# apiVersion: skaffold/v2alpha3
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   local:
#     push: false
#   artifacts:
#     - image: nightofserenity/client
#       context: client
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - dest: .
#             src: "src/**/*.js"
#     - image: nightofserenity/comments
#       context: comments
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - dest: .
#             src: "*.js"
#     - image: nightofserenity/event-bus
#       context: event-bus
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - dest: .
#             src: "*.js"
#     - image: nightofserenity/moderation
#       context: moderation
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - dest: .
#             src: "*.js"
#     - image: nightofserenity/posts
#       context: posts
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - dest: .
#             src: "*.js"
#     - image: nightofserenity/query
#       context: query
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - dest: .
#             src: "*.js"
